import {HandlerBtc} from "./Handlers/HandlerBtc";
import {ERC20Handler, HandlerEth} from "./Handlers/HandlerEth";
import {HandlerBtcTest} from "./Handlers/HandlerBtcTest";
import {ERC20TestHandler, HandlerEthTest} from "./Handlers/HandlerEthTest";
import {BaseCoinHandler, OnlineCoinHandler} from "./Handlers/BaseCoinHandler";
import {HandlerLtc} from "./Handlers/HandlerLtc";
import {HandlerDoge} from "./Handlers/HandlerDoge";
import {Engine} from "./Engine";
import {PortfolioOnlyHandler} from "./Handlers/PortfolioOnlyHandler";
import {HandlerDash} from "./Handlers/HandlerDash";
import {BEP20Handler, HandlerBnb} from "./Handlers/HandlerBnb";

export function createAllCoinHandlers(engine: Engine) : { [code: string] : BaseCoinHandler } {
    return {
        'BTC': new HandlerBtc(engine),
        'BTC.TST': new HandlerBtcTest(engine),
        'ETH': new HandlerEth(engine),
        'ETH.TST': new HandlerEthTest(engine),
        'LTC': new HandlerLtc(engine),
        'DOGE': new HandlerDoge(engine),
        'DASH': new HandlerDash(engine),
        'ERC20.TST': new ERC20TestHandler(
            engine,
            'ERC20.TST',
            'ERC20 Test Tokens',
            'erc20.tst',
            '0x251735ff853720582345c64cdb4eb44bd02e61a2',
            18
        ),
        'WEENUS.TST': new ERC20TestHandler(
            engine,
            'WEENUS.TST',
            'WEENUS Test Tokens',
            'noicon',
            '0x101848D5C5bBca18E6b4431eEdF6B95E9ADF82FA',
            18
        ),
        'YEENUS.TST': new ERC20TestHandler(
            engine,
            'YEENUS.TST',
            'YEENUS Test Tokens',
            'noicon',
            '0xF6fF95D53E08c9660dC7820fD5A775484f77183A',
            8
        ),
        'ZEENUS.TST': new ERC20TestHandler(
            engine,
            'ZEENUS.TST',
            'ZEENUS Test Tokens',
            'noicon',
            '0xC84f8B669Ccb91C86AB2b38060362b9956f2De52',
            0
        ),

        /* ERC20 Tokens */
        'BNB': new ERC20Handler(engine, 'BNB', 'BNB', 'Binance Coin', 'bnb.erc20', '0xB8c77482e45F1F44dE1745F52C74426C631bDD52', 18, 'Binance aims to build a world-class crypto exchange, powering the future of crypto finance.	', 'https://www.binance.com/', 'bnb-binance-coin', 'binancecoin', 'binance-coin' ),
        'VEN': new ERC20Handler(engine, 'VEN', 'VEN', 'VeChain', 'ven', '0xd850942ef8811f2a866692a623011bde52a462c1', 18, 'VeChain aims to connect blockchain technology to the real world by providing a comprehensive governance structure, a robust economic model as well as advanced IoT integration.	', "https://www.vechain.org/", '', '', ''),
        'MKR': new ERC20Handler(engine, 'MKR', 'MKR', 'Maker', 'mkr', '0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2', 18, 'Maker is a Decentralized Autonomous Organization that creates and insures the dai stablecoin on the Ethereum blockchain', 'https://makerdao.com/', 'mkr-maker', 'maker', 'maker'),
        'OMG': new ERC20Handler(engine, 'OMG', 'OMG', 'OmiseGO', 'omg', '0xd26114cd6EE289AccF82350c8d8487fedB8A0C07', 18, 'OmiseGO (OMG) is a public Ethereum-based financial technology for use in mainstream digital wallets', 'https://omg.network/', 'omg-omg-network', 'omisego', 'omg'),
        'ZRX': new ERC20Handler(engine, 'ZRX', 'ZRX', '0x', 'zrx', '0xe41d2489571d322189246dafa5ebde1f4699f498', 18, 'The Protocol for Trading Tokens', 'https://0x.org/', 'zrx-0x', '0x', '0x'),
        'TUSD': new ERC20Handler(engine, 'TUSD', 'TUSD', 'TrueUSD', 'tusd', '0x8dd5fbce2f6a956c3022ba3663759011dd51e73e', 18, 'The TrustToken Platform aims to be the bridge between blockchains and real-world assets.', 'https://www.trueusd.com/', 'tusd-trueusd', 'true-usd', 'trueusd'),
        'BAT': new ERC20Handler(engine, 'BAT', 'BAT', 'Basic Attention Token', 'bat', '0x0d8775f648430679a709e98d2b0cb6250d2887ef', 18, 'The Basic Attention Token is the new token for the digital advertising industry.', 'https://basicattentiontoken.org/', 'bat-basic-attention-token', 'basic-attention-token', 'basic-attention-token'),
        'PAX': new ERC20Handler(engine, 'PAX', 'PAX', 'Paxos Standard', 'pax', '0x8e870d67f660d95d5be530380d0ec0bd388289e1', 18, 'Paxos Standard is regulated crypto asset. It is fully collateralized 1:1 by the U.S. dollar, approved and regulated by the NYDFS, and enables instantaneous transactions.', 'https://paxos.com/standard/', 'pax-paxos-standard-token', 'paxos-standard', 'paxos-standard'),
        'USDC': new ERC20Handler(engine, 'USDC', 'USDC', 'USD Coin', 'usdc', '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48', 6, 'USDC is a fully collateralized US Dollar stablecoin developed by CENTRE, the open source project and membership consortium, with Circle being the first of several forthcoming issuers.', 'https://www.centre.io/usdc/', 'usdc-usd-coin', 'usd-coin', 'usd-coin'),
        'ZIL': new ERC20Handler(engine, 'ZIL', 'ZIL', 'Zilliqa', 'zil', '0x05f4a42e251f2d52b8ed15e9fedaacfcef1fad27', 12, 'Zilliqa is a high-throughput public blockchain platform - designed to scale to thousands ​of transactions per second.', 'https://www.zilliqa.com/', 'zil-zilliqa', 'zilliqa', 'zilliqa'),
        'AE': new ERC20Handler(engine, 'AE', 'AE', 'Aeternity', 'ae', '0x5ca9a71b1d01849c0a95490cc00559717fcf0d1d', 18, 'Scalable smart contracts interfacing with real world data.', 'https://www.aeternity.com/', 'ae-aeternity', 'aeternity', 'aeternity'),
        'ICX': new ERC20Handler(engine, 'ICX', 'ICX', 'ICON', 'icx', '0xb5a5f22694352c15b00323844ad545abb2b11028', 18, 'The ICON Network is comprised of various institutions ranging from: financial institutions, insurance companies, hospitals, universities and more.', 'https://iconrepublic.org/', 'icx-icon', 'icon', 'icon'),
        'AOA': new ERC20Handler(engine, 'AOA', 'AOA', 'Aurora', 'aoa', '0x9ab165d795019b6d8b3e971dda91071421305e5a', 18, 'Aurora Chain offers intelligent application isolation and enables multi-chain parallel expansion to create an extremely high TPS with security maintain.','https://www.aurorachain.io/', 'aoa-aurora', 'aurora', 'aurora'),
        'LINK': new ERC20Handler(engine, 'LINK', 'LINK', 'ChainLink Token', 'link', '0x514910771af9ca656af840dff83e8264ecf986ca', 18, 'The LINK Network provides smart contracts with data, bank payments and access to APIs.', 'https://chain.link/', 'link-chainlink', 'chainlink', 'chainlink'),
        'NPXS': new ERC20Handler(engine, 'NPXS', 'NPXS', 'Pundi X', 'npxs', '0xa15c7ebe1f07caf6bff097d8a589fb8ac49ae5b3', 18, '','https://pundix.com/', 'npxs-pundi-x', 'pundi-x', 'pundi-x' ),
        'BTM': new ERC20Handler(engine, 'BTM', 'BTM', 'Bytom', 'btm', '0xcb97e65f07da24d46bcdd078ebebd7c6e6e3d750', 8, 'Transfer assets from atomic world to byteworld', 'http://bytom.io/', 'btm-bytom', 'bytom', 'bytom'),
        'GNT': new ERC20Handler(engine, 'GNT', 'GLM', 'Golem', 'gnt', '0x7DD9c5Cba05E151C895FDe1CF355C9A1D5DA6429', 18, 'Golem is going to create the first decentralized global market for computing power	', 'https://golem.network/', 'glm-golem', 'golem', 'golem-network-tokens'),
        'REP': new ERC20Handler(engine, 'REP', 'REP', 'Augur', 'rep', '0x1985365e9f78359a9B6AD760e32412f4a445E862', 18, 'Augur combines the magic of prediction markets with the power of a decentralized network to create a stunningly accurate forecasting tool', 'http://www.augur.net/', 'rep-augur', 'augur', 'augur'),
        'PPT': new ERC20Handler(engine, 'PPT', 'PPT', 'Populous', 'ppt', '0xd4fa1460f537bb9085d22c7bccb5dd450ef28e3a', 8, 'Aims to rebuild invoice financing block by block, for invoice buyers and sellers.	', 'https://populous.world/', 'ppt-populous', 'populous', 'populous'),
        'QASH': new ERC20Handler(engine, 'QASH', 'QASH', 'QASH', 'qash', '0x618e75ac90b12c6049ba3b27f5d5f8651b0037f6', 6, 'We envision QASH to be the preferred payment token for financial services, like the Bitcoin for financial services. As more financial institutions, fintech startups and partners adopt QASH as a method of payment, the utility of QASH will scale, fueling the Fintech revolution.	', 'https://www.liquid.com/', 'qash-qash', 'qash', 'qash'),
        'MCO': new ERC20Handler(engine, 'MCO', 'MCO', 'Crypto.com', 'mco', '0xb63b606ac810a52cca15e44bb630fd42d8d1d83d', 8, 'Crypto.com, the pioneering payments and cryptocurrency platform, seeks to accelerate the world’s transition to cryptocurrency.	', 'https://mco.crypto.com/', 'mco-mco', '', 'crypto-com'),
        'HOT': new ERC20Handler(engine, 'HOT', 'HOT', 'HoloToken', 'hot', '0x6c6ee5e31d828de241282b9606c8e98ea48526e2', 18, 'Holo is a decentralized hosting platform and a new breed of asset-backed, mutual-credit cryptocurrency based on Holochain. Holochain is a massively scalable, agent-centric post-blockchain development framework for distributed applications.	', 'https://holo.host/', 'hot-holo', 'holotoken', 'holo'),
        'GUSD': new ERC20Handler(engine, 'GUSD', 'GUSD', 'Gemini dollar', 'gusd', '0x056fd409e1d7a124bd7017459dfea2f387b6d5cd', 2, 'Gemini dollar combines the creditworthiness and price stability of the U.S. dollar with blockchain technology and the oversight of U.S. regulators.	', 'https://gemini.com/dollar/', 'gusd-gemini-dollar', 'gemini-dollar', 'gemini-dollar'),
        'DAI': new ERC20Handler(engine, 'DAI', 'DAI', 'Dai', 'dai', '0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359', 18, '', 'http://www.makerdao.com/', 'dai-dai', 'dai', 'multi-collateral-dai'),
        'WAX': new ERC20Handler(engine, 'WAX', 'WAX', 'WAX Token', 'wax', '0x39bb259f66e1c59d5abef88375979b4d20d98022', 8, 'Global Decentralized Marketplace for Virtual Assets.', 'https://wax.io/', 'wax-wax', 'wax', 'wax'),
        'SNT': new ERC20Handler(engine, 'SNT', 'SNT', 'Status', 'snt', '0x744d70fdbe2ba4cf95131626614a1763df805b9e', 18, 'Status is an open source messaging platform and mobile browser to interact with decentralized applications that run on the Ethereum Network.	', 'http://status.im/', 'snt-status', 'status', 'status'),
        'MANA': new ERC20Handler(engine, 'MANA', 'MANA', 'Decentraland', 'mana', '0x0f5d2fb29fb7d3cfee444a200298f468908cc942', 18, 'Decentraland is a virtual reality platform powered by the Ethereum blockchain. Users can create, experience, and monetize content and applications	', 'https://decentraland.org/', 'mana-decentraland', 'decentraland', 'decentraland'),
        'HT': new ERC20Handler(engine, 'HT', 'HT', 'Huobi Token', 'ht', '0x6f259637dcd74c767781e37bc6133cd6a68aa161', 18, 'Huobi Global is a world-leading cryptocurrency financial services group.', 'https://www.hbg.com/', 'ht-huobi-token', 'huobi-token', 'huobi-token'),
        'REV': new ERC20Handler(engine, 'REV', 'REV', 'Revain', 'rev', '0x2ef52Ed7De8c5ce03a4eF0efbe9B7450F2D7Edc9', 6, 'Revain is blockchain-based review platform for crypto community. Since 2018 we accumulated the biggest number of user feedback on crypto on the Internet.', 'https://revain.org/', 'rev-revain', 'revain', 'revain'),
        'IOST': new ERC20Handler(engine, 'IOST', 'IOST', 'IOSToken', 'iost', '0xfa1a856cfa3409cfa145fa4e20eb270df3eb21ab', 18, 'A Secure & Scalable Blockchain for Smart Services	', 'http://iost.io/', 'iost-iost', 'iostoken', 'iostoken'),
        'ODE': new ERC20Handler(engine, 'ODE', 'ODE', 'ODEM', 'ode', '0xbf52f2ab39e26e0951d2a02b49b7702abe30406a', 18, 'Unlocking human potential. Powering your education and certifications on the blockchain	', 'https://odem.io/', 'ode-odem', 'odem', 'odem'),
        'MGO': new ERC20Handler(engine, 'MGO', 'MGO', 'MobileGo', 'mgo', '0x40395044Ac3c0C57051906dA938B54BD6557F212', 8, 'A dedicated token to bring eSports to everyone.	', 'https://mobilego.io/', 'mgo-mobilego', 'mobilego', 'mobilego'),
        'NEXO': new ERC20Handler(engine, 'NEXO', 'NEXO', 'Nexo', 'nexo', '0xb62132e35a6c13ee1ee0f84dc5d40bad8d815206', 18, 'Instant Crypto-backed Loans', 'http://nexo.io/', 'nexo-nexo', 'nexo', 'nexo'),
        'WTC': new ERC20Handler(engine, 'WTC', 'WTC', 'Walton', 'wtc', '0xb7cb1c96db6b22b0d3d9536e0108d062bd488f74', 18, 'Value Internet of Things (VIoT) constructs a perfect commercial ecosystem via the integration of the real world and the blockchain.	', 'http://www.waltonchain.org/', 'wtc-waltonchain', 'waltonchain', 'waltonchain'),
        'PRL': new ERC20Handler(engine, 'PRL', 'PRL', 'Oyster Pearl', 'prl', '0x1844b21593262668b7248d0f57a220caaba46ab9', 18, 'Platform for website monetization and distributed storage, built on IOTA Tangle and Ethereum.', "https://oysterprotocol.com/", 'prl-oyster', '', 'oyster'),
        'INB': new ERC20Handler(engine, 'INB', 'INB', 'Insight Chain', 'inb', '0x17aa18a4b64a55abed7fa543f2ba4e91f2dce482', 18, 'Insight Chain is an EOS-based data ecosystem on the blockchain, works on building Wall Street-like financial order in the blockchain domain.	', 'http://www.insightchain.io/', 'inb-insight-chain', 'insight-chain', 'insight-chain'),
        'POLY': new ERC20Handler(engine, 'POLY', 'POLY', 'Polymath', 'poly', '0x9992ec3cf6a55b00978cddf2b27bc6882d88d1ec', 18, 'Polymath aims to enable securities to migrate to the blockchain.	', 'https://www.polymath.network/', 'poly-polymath', 'polymath-network', 'polymath-network'),
        'THETA': new ERC20Handler(engine, 'THETA', 'THETA', 'Theta Token', 'theta', '0x3883f5e181fccaf8410fa61e12b59bad963fb645', 18, 'A decentralized peer-to-peer network that aims to offer improved video delivery at lower costs.	', 'https://www.thetatoken.org/', 'theta-theta-token', 'theta-token', 'theta'),
        'AION': new ERC20Handler(engine, 'AION', 'AION', 'AION', 'aion', '0x4CEdA7906a5Ed2179785Cd3A40A69ee8bc99C466', 8, 'A multi-tier blockchain system designed to address unsolved questions of scalability, privacy, and interoperability in blockchain networks	', 'https://theoan.com/', 'aion-aion', 'aion', 'aion'),
        'BNT': new ERC20Handler(engine, 'BNT', 'BNT', 'Bancor', 'bnt', '0x1f573d6fb3f13d689ff844b4ce37794d79a7ff1c', 18, 'Bancor Protocol is a standard for a new generation of cryptocurrencies called Smart Tokens	', 'https://bancor.network/', 'bnt-bancor', 'bancor', 'bancor' ),
        'LKY': new ERC20Handler(engine, 'LKY', 'LKY', 'Linkey Token', 'lky', '0x49bd2da75b1f7af1e4dfd6b1125fecde59dbec58', 18, 'A platform to connect digital assets to real community.	', "https://www.linkey.info/" ,'lky-linkey','','linkey'),
        'ELF': new ERC20Handler(engine, 'ELF', 'ELF', 'aelf', 'elf', '0xbf2179859fc6d5bee9bf9158632dc51678a4100e', 18, 'elf is a decentralized self-evolving cloud computing blockchain network that aims to provide a high performance platform for commercial adoption of blockchain.	', 'http://aelf.io/', 'elf-aelf', 'aelf', 'aelf'),
        'QKC': new ERC20Handler(engine, 'QKC', 'QKC', 'QuarkChain', 'qkc', '0xea26c4ac16d4a5a106820bc8aee85fd0b7b2b664', 18, 'A High-Capacity Peer-to-Peer Transactional System	', 'https://quarkchain.io/', 'qkc-quarkchain', 'quark-chain', 'quarkchain'),
        'LRC': new ERC20Handler(engine, 'LRC', 'LRC', 'Loopring', 'lrc', '0xef68e7c694f40c8202821edf525de3782458639f', 18, 'Loopring is not only a protocol but also a decentralized automated execution system that trades across the crypto-token exchanges.	', 'https://loopring.org/', 'lrc-loopring', 'loopring', 'loopring'),
        'PAY': new ERC20Handler(engine, 'PAY', 'PAY', 'TenX', 'pay', '0xB97048628DB6B661D4C2aA833e95Dbe1A905B280', 18, 'TenX connects your blockchain assets for everyday use. TenX’s debit card and banking licence will allow us to be a hub for the blockchain ecosystem to connect for real-world use cases.', 'https://www.tenx.tech/', 'pay-tenx', 'tenx', 'tenx'),
        'CFT': new ERC20Handler(engine, 'CFT', 'CFT', 'Coffee Token', 'cft', '0x5bf2390a68ab7db7d27ae81894c4e22e669af236', 18, 'Coffee Token is an utility token for Coffee Wallet Project.', "https://tokens.coffee/", 'cft-coffee-token', '', 'coffee-token'),
        'KLOWN': new ERC20Handler(engine, 'KLOWN', 'KLOWN', 'Ether Clown', 'klown', '0xc97a5cdf41bafd51c8dbe82270097e704d748b92', 7, 'Ether Clown is a social experiment type of a token with an RNG (Random Number Generated) burning mechanism on every transaction from 1.5% to 3.5% when people transfer token(s) between two addresses.', "https://etherclown.com/", '','',''),
        'FRECNX': new ERC20Handler(engine, 'FRECNX', 'FRECNX', 'FreldoCoinX', 'frecnx', '0xd8b8e1eca89da014e67fdbc2014eaa8e171079bf', 18, 'Freldo (FRECNX) – fully functional global network linking service providers and clients to eliminate fraud reviews and provide lower prices for customers. Our goal is to make a revolution in the services market by implementing blockchain technology to the business-client relationship, providing small business with the tools of large networks and companies. FRECNX is utility token and can be used as a means of payment within the Freldo business platform. Freldo Inc. registered in Toronto, Canada in 2011', "https://ico.freldo.com/", 'frecnx-freldocoinx', '', 'freldo'),
        'NOW': new ERC20Handler(engine, 'NOW', 'NOW', 'ChangeNOW', 'now', '0xe9a95d175a5f4c9369f3b74222402eb1b837693b', 8, 'NOW Token is the first token made by an instant exchange platform. NOW Tokens serve as an internal currency on NOW products. As ChangeNOW grows extremely fast, the tokens will be in a great demand.', 'https://changenow.io/', 'now-changenow', '', 'now-token' ),
        'USDT': new ERC20Handler(engine, 'USDT', 'USDT', 'Tether USD', 'usdt', '0xdac17f958d2ee523a2206206994597c13d831ec7', 6, '', 'https://tether.to/', 'usdt-tether', 'tether', 'tether'),
        'LEO': new ERC20Handler(engine, 'LEO', 'LEO', 'Bitfinex LEO Token', 'leo', '0x2af5d2ad76741191d15dfe7bf6ac92d4bd912ca3', 18, 'A utility token designed to empower the Bitfinex community and provide utility for those seeking to maximize the output and capabilities of the Bitfinex trading platform.', 'https://www.bitfinex.com/', 'leo-leo-token', 'leo-token', 'unus-sed-leo'),
        'WBTC': new ERC20Handler(engine, 'WBTC', 'WBTC', 'Wrapped BTC', 'wbtc', '0x2260fac5e5542a773aa44fbcfedf7c193bc2c599', 8, 'Wrapped Bitcoin (WBTC) is an ERC20 token backed 1:1 with Bitcoin. Completely transparent. 100% verifiable. Community led.',  'https://wbtc.network/', 'wbtc-wrapped-bitcoin', 'wrapped-bitcoin', 'wrapped-bitcoin' ),
        'CRO': new ERC20Handler(engine, 'CRO', 'CRO', 'Crypto.com Coin', 'cro', '0xa0b73e1ff0b80914ab6fe0444e65848c4c34450b', 8, 'Pay and be paid in crypto anywhere, with any crypto, for free.', 'https://www.crypto.com/en/chain/', 'cro-cryptocom-chain', 'crypto-com-chain', 'crypto-com-coin'),
        'CEL': new ERC20Handler(engine, 'CEL', 'CEL', 'Celsius', 'cel', '0xaaaebe6fe48e54f431b0c390cfaf0b017d09d42d', 4, 'A new way to earn, borrow, and pay on the blockchain.!', 'https://celsius.network/', 'cel-celsius', 'celsius-degree-token', 'celsius'),
        'UNI': new ERC20Handler(engine, 'UNI', 'UNI', 'Uniswap', 'uni', '0x1f9840a85d5af5bf1d1762f925bdaddc4201f984', 18, 'UNI token served as governance token for Uniswap protocol with 1 billion UNI have been minted at genesis. 60% of the UNI genesis supply is allocated to Uniswap community members and remaining for team, investors and advisors.', 'https://uniswap.org/', 'uni-uniswap', 'uniswap', 'uniswap'),
        'SNX': new ERC20Handler(engine, 'SNX', 'SNX', 'Synthetix Network Token', 'snx', '0xc011a73ee8576fb46f5e1c5751ca3b9fe0af2a6f', 18, 'The Synthetix Network Token (SNX) is the native token of Synthetix, a synthetic asset (Synth) issuance protocol built on Ethereum. The SNX token is used as collateral to issue Synths, ERC-20 tokens that track the price of assets like Gold, Silver, Oil and Bitcoin.', 'https://www.synthetix.io/', 'snx-synthetix-network-token', 'havven', 'synthetix-network-token'),


        'BNB.2': new HandlerBnb(engine),
        //BEP20 tokens
        'BUSD': new BEP20Handler(engine, 'BUSD', 'BUSD', 'Binance USD', 'busd', '0xe9e7cea3dedca5984780bafc599bd69add087d56', 18, 'Binance USD (BUSD) is a USD-denominated stablecoin approved by the New York State Department of Financial Services (NYDFS) that was launched in partnership with Paxos and Binance.', 'https://www.paxos.com/busd/', 'busd-binance-usd', 'binance-usd', 'binance-usd'),
        'CAKE': new BEP20Handler(engine, 'CAKE', 'CAKE', 'PancakeSwap Token', 'cake', '0x0e09fabb73bd3ade0a17ecc321fd13a19e81ce82', 18, 'PancakeSwap is an automated market maker (AMM) — a decentralized finance (DeFi) application that allows users to exchange tokens, providing liquidity via farming and earning fees in return.', 'https://pancakeswap.finance/', 'cake-pancakeswap', 'pancakeswap', 'pancakeswap'),
        'BAKE': new BEP20Handler(engine, 'BAKE', 'BAKE', 'BakeryToken', 'bake', '0xe02df9e3e622debdd69fb838bb799e3f168902c5', 18, 'Launched in September 2020, BakeryToken (BAKE) is a part of the BakerySwap ecosystem. Liquidity providers are rewarded with BAKE tokens which can be used to earn a share of BakerySwap\'s trading fees and to participate in voting as part of BakerySwap’s governance process.', 'https://www.bakeryswap.org/', 'bake-bakeryswap', 'bakeryswap', 'bakerytoken'),
        '1INCH': new BEP20Handler(engine, '1INCH', '1INCH', '1inch', '1inch', '0x111111111117dc0aa78b770fa6a738034120c302', 18, '1inch exchange is a decentralized exchange (DEX) aggregator to help users discover the best trade prices for tokens.', 'https://1inch.io/', '1inch-1inch', '1inch', '1inch'),

        //PORTFOLIO
        'BCH.TST': new PortfolioOnlyHandler('BCH.TST', 'BCH.TST', 'Bitcoin Cash TestNet', 'bch.test' ),

        //'1INCH': new PortfolioOnlyHandler('1INCH', '1INCH', '1inch', 'noicon', 'https://1inch.io/', '1inch-1inch', '1inch', '1inch' ),
        'AAVE': new PortfolioOnlyHandler('AAVE', 'AAVE', 'Aave', 'noicon', 'https://aave.com/', 'aave-new', 'aave', 'aave' ),
        'ADA': new PortfolioOnlyHandler('ADA', 'ADA', 'Cardano', 'ada', 'https://www.cardano.org/', 'ada-cardano', 'cardano', 'cardano' ),
        'ALGO': new PortfolioOnlyHandler('ALGO', 'ALGO', 'Algorand', 'algo', 'https://algorand.foundation/', 'algo-algorand', 'algorand', 'algorand' ),
        'AMP': new PortfolioOnlyHandler('AMP', 'AMP', 'Amp', 'amp', 'https://amptoken.org/', 'amp-amp', 'amp-token', 'amp' ),
        'ANKR': new PortfolioOnlyHandler('ANKR', 'ANKR', 'Ankr', 'noicon', 'https://www.ankr.com/', 'ankr-ankr-network', 'ankr', 'ankr' ),
        'AR': new PortfolioOnlyHandler('AR', 'AR', 'Arweave', 'noicon', 'https://arweave.org/', 'ar-arweave', 'arweave', 'arweave' ),
        'ARRR': new PortfolioOnlyHandler('ARRR', 'ARRR', 'Pirate', 'noicon', 'https://pirate.black/', 'arrr-pirate', 'pirate-chain', 'pirate-chain' ),
        'ATOM': new PortfolioOnlyHandler('ATOM', 'ATOM', 'Cosmos', 'atom', 'https://cosmos.network/', 'atom-cosmos', 'cosmos', 'cosmos' ),
        'AVAX': new PortfolioOnlyHandler('AVAX', 'AVAX', 'Avalanche', 'noicon', 'https://www.avalabs.org/', 'avax-avalanche', 'avalanche-2', 'avalanche' ),
        'BCD': new PortfolioOnlyHandler('BCD', 'BCD', 'Bitcoin Diamond', 'bcd', 'http://btcd.io/', 'bcd-bitcoin-diamond', 'bitcoin-diamond', 'bitcoin-diamond' ),
        'BCH': new PortfolioOnlyHandler('BCH', 'BCH', 'Bitcoin Cash', 'bch', 'https://bch.info/', 'bch-bitcoin-cash', 'bitcoin-cash', 'bitcoin-cash' ),
        'BEST': new PortfolioOnlyHandler('BEST', 'BEST', 'Bitpanda Ecosystem Token', 'noicon', 'https://www.bitpanda.com/en/best/', 'best-bitpanda-ecosystem-token', 'bitpanda-ecosystem-token', 'bitpanda-ecosystem-token' ),
        'BSV': new PortfolioOnlyHandler('BSV', 'BSV', 'Bitcoin SV', 'bsv', 'https://bitcoinsv.com/', 'bsv-bitcoin-sv', 'bitcoin-cash-sv', 'bitcoin-sv' ),
        'BTCB': new PortfolioOnlyHandler('BTCB', 'BTCB', 'Bitcoin BEP2', 'noicon', 'https://www.binance.com/en/blog/347360878904684544/Introducing-BitcoinPegged-Token-on-Binance-Chain/', 'btcb-bitcoin-bep2', 'bitcoin-bep2', 'bitcoin-bep2' ),
        'BTG': new PortfolioOnlyHandler('BTG', 'BTG', 'Bitcoin Gold', 'btg', 'https://bitcoingold.org/', 'btg-bitcoin-gold', 'bitcoin-gold', 'bitcoin-gold' ),
        'BTT': new PortfolioOnlyHandler('BTT', 'BTT', 'BitTorrent', 'btt', 'https://www.bittorrent.com/btt/', 'btt-bittorrent', 'bittorrent-2', 'bittorrent' ),
        //'BUSD': new PortfolioOnlyHandler('BUSD', 'BUSD', 'Binance USD', 'noicon', 'https://www.paxos.com/busd/', 'busd-binance-usd', 'binance-usd', 'binance-usd' ),
        //'CAKE': new PortfolioOnlyHandler('CAKE', 'CAKE', 'PancakeSwap', 'noicon', 'https://pancakeswap.finance/', 'cake-pancakeswap', 'pancakeswap-token', 'pancakeswap' ),
        'CDAI': new PortfolioOnlyHandler('CDAI', 'CDAI', 'cDAI', 'noicon', 'https://compound.finance/', '', 'cdai', '' ),
        'CELO': new PortfolioOnlyHandler('CELO', 'CELO', 'Celo', 'noicon', 'https://celo.org/', '', 'celo', 'celo' ),
        'CETH': new PortfolioOnlyHandler('CETH', 'CETH', 'cETH', 'noicon', 'https://compound.finance/', '', 'compound-ether', '' ),
        'CHSB': new PortfolioOnlyHandler('CHSB', 'CHSB', 'SwissBorg', 'noicon', 'https://swissborg.com/', 'chsb-swissborg', 'swissborg', 'swissborg' ),
        'CHZ': new PortfolioOnlyHandler('CHZ', 'CHZ', 'Chiliz', 'noicon', 'https://www.chiliz.com/', 'chz-chiliz', 'chiliz', 'chiliz' ),
        'COMP': new PortfolioOnlyHandler('COMP', 'COMP', 'Compound', 'comp', 'https://compound.finance/governance/comp/', 'comp-compoundd', 'compound-governance-token', 'compound' ),
        'CSC': new PortfolioOnlyHandler('CSC', 'CSC', 'CasinoCoin', 'noicon', 'http://casinocoin.org/', 'csc-casinocoin', 'casinocoin', 'casinocoin' ),
        'CUSDC': new PortfolioOnlyHandler('CUSDC', 'CUSDC', 'cUSDC', 'noicon', 'https://compound.finance/', '', 'compound-usd-coin', '' ),
        'CVNT': new PortfolioOnlyHandler('CVNT', 'CVNT', 'Content Value Network', 'noicon', 'http://cvn.io/', 'cvnt-content-value-network', 'content-value-network', 'content-value-network' ),
        'DCR': new PortfolioOnlyHandler('DCR', 'DCR', 'Decred', 'dcr', 'https://www.decred.org/', 'dcr-decred', 'decred', 'decred' ),
        'DENT': new PortfolioOnlyHandler('DENT', 'DENT', 'Dent', 'dent', 'https://www.dentwireless.com/', 'dent-dent', 'dent', 'dent' ),
        'DFI': new PortfolioOnlyHandler('DFI', 'DFI', 'DeFi Chain', 'noicon', 'https://defichain.com/', 'dfi-defi-chain', 'defichain', 'defichain' ),
        'DGB': new PortfolioOnlyHandler('DGB', 'DGB', 'DigiByte', 'dgb', 'https://digibyte.org/', 'dgb-digibyte', 'digibyte', 'digibyte' ),
        'DOT': new PortfolioOnlyHandler('DOT', 'DOT', 'Polkadot', 'dot', 'https://polkadot.network/', 'dot-polkadot', 'polkadot', 'polkadot-new' ),
        'EGLD': new PortfolioOnlyHandler('EGLD', 'EGLD', 'Elrond', 'noicon', 'https://elrond.com/', 'egld-elrond', 'elrond-erd-2', 'elrond-egld' ),
        'ENJ': new PortfolioOnlyHandler('ENJ', 'ENJ', 'Enjin Coin', 'enj', 'https://enjin.io/', 'enj-enjin-coin', 'enjincoin', 'enjin-coin' ),
        'EOS': new PortfolioOnlyHandler('EOS', 'EOS', 'EOS', 'eos', 'https://eos.io/', 'eos-eos', 'eos', 'eos' ),
        'ETC': new PortfolioOnlyHandler('ETC', 'ETC', 'Ethereum Classic', 'etc', 'https://ethereumclassic.org/', 'etc-ethereum-classic', 'ethereum-classic', 'ethereum-classic' ),
        'FIL': new PortfolioOnlyHandler('FIL', 'FIL', 'Filecoin', 'fil', 'https://filecoin.io/', 'fil-filecoin', 'filecoin', 'filecoin' ),
        'FLOW': new PortfolioOnlyHandler('FLOW', 'FLOW', 'Flow', 'noicon', 'https://www.onflow.org/', 'flow-flow1141', 'flow', 'flow' ),
        'FTM': new PortfolioOnlyHandler('FTM', 'FTM', 'Fantom', 'noicon', 'https://fantom.foundation/', 'ftm-fantom', 'fantom', 'fantom' ),
        'FTT': new PortfolioOnlyHandler('FTT', 'FTT', 'FTX Token', 'noicon', 'https://ftx.com/', 'ftt-ftx-token', 'ftx-token', 'ftx-token' ),
        'GRT': new PortfolioOnlyHandler('GRT', 'GRT', 'The Graph', 'noicon', 'https://thegraph.com/', 'grt-the-graph', 'the-graph', 'the-graph' ),
        'HBAR': new PortfolioOnlyHandler('HBAR', 'HBAR', 'Hedera Hashgraph', 'noicon', 'https://www.hedera.com/', 'hbar-hedera-hashgraph', 'hedera-hashgraph', 'hedera-hashgraph' ),
        'HBTC': new PortfolioOnlyHandler('HBTC', 'HBTC', 'Huobi BTC', 'noicon', 'https://www.hbtc.finance/', '', 'huobi-btc', 'huobi-btc' ),
        'HEX': new PortfolioOnlyHandler('HEX', 'HEX', 'HEX', 'noicon', 'https://hex.com/', 'hex-hex', 'hex', 'hex' ),
        'HNT': new PortfolioOnlyHandler('HNT', 'HNT', 'Helium', 'noicon', 'https://www.helium.com/', 'hnt-helium', 'helium', 'helium' ),
        'KCS': new PortfolioOnlyHandler('KCS', 'KCS', 'KuCoin Token', 'kcs', 'https://www.kucoin.com/', 'kcs-kucoin-token', 'kucoin-shares', 'kucoin-token' ),
        'KLAY': new PortfolioOnlyHandler('KLAY', 'KLAY', 'Klaytn', 'noicon', 'https://www.klaytn.com/', '', 'klay-token', 'klaytn' ),
        'KSM': new PortfolioOnlyHandler('KSM', 'KSM', 'Kusama', 'noicon', 'https://kusama.network/', 'ksm-kusama', 'kusama', 'kusama' ),
        'LEND': new PortfolioOnlyHandler('LEND', 'LEND', 'Aave', 'lend', 'https://aave.com/', 'lend-ethlend', 'aave', 'aave' ),
        'LSK': new PortfolioOnlyHandler('LSK', 'LSK', 'Lisk', 'lsk', 'https://lisk.io/', 'lsk-lisk', 'lisk', 'lisk' ),
        'LUNA': new PortfolioOnlyHandler('LUNA', 'LUNA', 'LUNA', 'noicon', 'https://terra.money/', 'luna-terra', 'terra-luna', 'terra-luna' ),
        'LUSD': new PortfolioOnlyHandler('LUSD', 'LUSD', 'Liquity USD', 'noicon', 'https://www.liquity.org/', '', 'liquity-usd', 'liquity-usd' ),
        'MATIC': new PortfolioOnlyHandler('MATIC', 'MATIC', 'Matic Network', 'matic', 'https://matic.network/', 'matic-matic-network', 'matic-network', 'polygon' ),
        'MIOTA': new PortfolioOnlyHandler('MIOTA', 'MIOTA', 'IOTA', 'miota', 'https://www.iota.org/', 'miota-iota', 'iota', 'iota' ),
        'NANO': new PortfolioOnlyHandler('NANO', 'NANO', 'Nano', 'nano', 'http://nano.org/en/', 'nano-nano', 'nano', 'nano' ),
        'NEAR': new PortfolioOnlyHandler('NEAR', 'NEAR', 'Near Protocol', 'noicon', 'https://nearprotocol.com/', 'near-near-protocol', 'near', 'near-protocol' ),
        'NEO': new PortfolioOnlyHandler('NEO', 'NEO', 'NEO', 'neo', 'https://neo.org/', 'neo-neo', 'neo', 'neo' ),
        'OKB': new PortfolioOnlyHandler('OKB', 'OKB', 'OKB', 'noicon', 'https://www.okex.com/', 'okb-okb', 'okb', 'okb' ),
        'ONE': new PortfolioOnlyHandler('ONE', 'ONE', 'Harmony', 'noicon', 'https://harmony.one/', 'one-harmony', 'harmony', 'harmony' ),
        'ONT': new PortfolioOnlyHandler('ONT', 'ONT', 'Ontology', 'ont', 'https://ont.io/', 'ont-ontology', 'ontology', 'ontology' ),
        'QTUM': new PortfolioOnlyHandler('QTUM', 'QTUM', 'Qtum', 'qtum', 'https://qtum.org/', 'qtum-qtum', 'qtum', 'qtum' ),
        'REN': new PortfolioOnlyHandler('REN', 'REN', 'Ren', 'ren', 'https://renproject.io/', 'ren-republic-protocol', 'republic-protocol', 'ren' ),
        'RUNE': new PortfolioOnlyHandler('RUNE', 'RUNE', 'THORChain', 'noicon', 'https://thorchain.org/', 'rune-thorchain', 'thorchain', 'thorchain' ),
        'RVN': new PortfolioOnlyHandler('RVN', 'RVN', 'Ravencoin', 'rvn', 'https://ravencoin.org/', 'rvn-ravencoin', 'ravencoin', 'ravencoin' ),
        'SC': new PortfolioOnlyHandler('SC', 'SC', 'Siacoin', 'sc', 'https://sia.tech/', 'sc-siacoin', 'siacoin', 'siacoin' ),
        'SOL': new PortfolioOnlyHandler('SOL', 'SOL', 'Solana', 'noicon', 'https://solana.com/', 'sol-solana', 'solana', 'solana' ),
        'STX': new PortfolioOnlyHandler('STX', 'STX', 'Blockstack', 'stx', 'http://stacks.co/', 'stx-blockstack', 'blockstack', 'stacks' ),
        'SUSHI': new PortfolioOnlyHandler('SUSHI', 'SUSHI', 'Sushi', 'noicon', 'https://sushiswap.org/', 'Sushi-sushi', 'sushi', 'sushiswap' ),
        'TEL': new PortfolioOnlyHandler('TEL', 'TEL', 'Telcoin', 'tel', 'https://www.telco.in/', 'tel-telcoin', 'telcoin', 'telcoin' ),
        'TFUEL': new PortfolioOnlyHandler('TFUEL', 'TFUEL', 'Theta Fuel', 'noicon', 'https://www.thetatoken.org/', 'tfuel-theta-fuel', 'theta-fuel', 'theta-fuel' ),
        'THR': new PortfolioOnlyHandler('THR', 'THR', 'ThoreCoin', 'noicon', 'https://www.thorecoin.com/', 'thr-thorecoin', 'thorecoin', 'thorecoin' ),
        'TRX': new PortfolioOnlyHandler('TRX', 'TRX', 'TRON', 'trx', 'https://tron.network/', 'trx-tron', 'tron', 'tron' ),
        'TTT': new PortfolioOnlyHandler('TTT', 'TTT', 'The Transfer Token', 'noicon', 'https://www.atom-solutions.jp/en/xecttt/', 'ttt-the-transfer-token', 'the-transfer-token', 'the-transfer-token' ),
        'UMA': new PortfolioOnlyHandler('UMA', 'UMA', 'UMA', 'uma', 'https://umaproject.org/', 'uma-uma', 'uma', 'uma' ),
        'UST': new PortfolioOnlyHandler('UST', 'UST', 'TerraUSD', 'noicon', 'https://terra.money/', 'ust-terrausd', 'terrausd', 'terrausd' ),
        'VET': new PortfolioOnlyHandler('VET', 'VET', 'VeChain', 'vet', 'https://www.vechain.org/', 'vet-vechain', 'vechain', 'vechain' ),
        'VGX': new PortfolioOnlyHandler('VGX', 'VGX', 'Voyager Token', 'noicon', 'https://www.investvoyager.com/', 'ethos-ethos', 'ethos', 'voyager-token' ),
        'WAVES': new PortfolioOnlyHandler('WAVES', 'WAVES', 'Waves', 'waves', 'https://waves.tech/', 'waves-waves', 'waves', 'waves' ),
        'XDCE': new PortfolioOnlyHandler('XDCE', 'XDCE', 'XinFin Network', 'noicon', 'https://www.xinfin.io/', 'xdce-xinfin-network', 'xdce-crowd-sale', '' ),
        'XEM': new PortfolioOnlyHandler('XEM', 'XEM', 'NEM', 'xem', 'http://nem.io/', 'xem-nem', 'nem', 'nem' ),
        'XLM': new PortfolioOnlyHandler('XLM', 'XLM', 'Stellar', 'xlm', 'https://www.stellar.org/', 'xlm-stellar', 'stellar', 'stellar' ),
        'XMR': new PortfolioOnlyHandler('XMR', 'XMR', 'Monero', 'xmr', 'https://getmonero.org/', 'xmr-monero', 'monero', 'monero' ),
        'XRP': new PortfolioOnlyHandler('XRP', 'XRP', 'XRP', 'xrp', 'https://ripple.com/xrp/', 'xrp-xrp', 'ripple', 'xrp' ),
        'XTZ': new PortfolioOnlyHandler('XTZ', 'XTZ', 'Tezos', 'xtz', 'https://www.tezos.com/', 'xtz-tezos', 'tezos', 'tezos' ),
        'XVG': new PortfolioOnlyHandler('XVG', 'XVG', 'Verge', 'xvg', 'http://vergecurrency.com/', 'xvg-verge', 'verge', 'verge' ),
        'XVS': new PortfolioOnlyHandler('XVS', 'XVS', 'Venus', 'noicon', 'https://venus.io/', '', 'venus', 'venus' ),
        'YFI': new PortfolioOnlyHandler('YFI', 'YFI', 'yearn.finance', 'yfi', 'https://yearn.finance/', 'yfi-yearnfinance', 'yearn-finance', 'yearn-finance' ),
        'ZEC': new PortfolioOnlyHandler('ZEC', 'ZEC', 'Zcash', 'zec', 'https://z.cash/', 'zec-zcash', 'zcash', 'zcash' ),
        'ZEN': new PortfolioOnlyHandler('ZEN', 'ZEN', 'Horizen', 'zen', 'https://horizen.global/', 'zen-horizen', 'zencash', 'horizen' ),

    }
}

export function isOnlineCoinHanlder(toBeDetermined: BaseCoinHandler): toBeDetermined is OnlineCoinHandler {
    return ('explorerLinkAddr' in (toBeDetermined as OnlineCoinHandler));
}
